### PR TITLE
Update deprecated option

### PR DESCRIPTION
**Pull request by robsonbittencourt**
sonarqube option in travis.yml should be replaced by sonarcloud

image

### CODE REVIEW

**Comment by robsonbittencourt** [comment]
Sorry I had not seen that the build had broken. I came back here today and I realized. I did a little research and I did not see any apparent reason why this happened ...

**Comment by kwart** [comment]
The deprecated `sonarqube` is able to skip the sonar analysis for external PRs, the new `sonarcloud` seems not to be able to do this.

https://github.com/wildfly-security/wildfly-elytron/pull/961#issuecomment-324619179

**Comment by kwart** [comment]
The change to `sonarcloud` addon name was already done in this project, so IMO this PR can be closed.

**Comment by robsonbittencourt** [comment]
You're right @kwart. Was fixed rwo days after my PR.

**Pull request closed without merging**
